export const sampleData= [
    {
        "url":"http://pbs.twimg.com/media/Df1XjdMW4AAgFOh.jpg",
        "type":"photo",
        "text":"https://t.co/qFMZed6Ii5",
        "user":"katipallyvinay",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1O2mFUEAAod76.jpg",
        "type":"photo",
        "text":"https://t.co/xEE4t7xt1W",
        "user":"isocialsaint",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DftoVifU8AAWpnI.jpg",
        "type":"photo",
        "text":"https://t.co/Dbmxac89uF",
        "user":"istam_na",
        "retweetCount":58
    },
    {
        "url":"http://pbs.twimg.com/media/Df1Iab-VMAA2760.jpg",
        "type":"photo",
        "text":"https://t.co/69TMA87Xlf",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1IN1gUcAA_Sds.jpg",
        "type":"photo",
        "text":"https://t.co/q1zmhWM6JS",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1HWqzU0AAfjkK.jpg",
        "type":"photo",
        "text":"https://t.co/47mo980xNR",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfgk2zTV4AADA3x.jpg",
        "type":"photo",
        "text":"https://t.co/UKIEVHvr1M",
        "user":"PranayOfficial",
        "retweetCount":116
    },
    {
        "url":"http://pbs.twimg.com/media/Df1GUceVQAAAjXU.jpg",
        "type":"photo",
        "text":"https://t.co/gSHhppU4Fx",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1008038739048722432/pu/img/sQXv-Z0bVYSYsAQN.jpg",
        "type":"photo",
        "text":"https://t.co/KEJne48jDT",
        "user":"JoshuaJoe95",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfuriA_VMAAvyO0.jpg",
        "type":"photo",
        "text":"https://t.co/STuTfcC3CF",
        "user":"nbkmyheart3",
        "retweetCount":6
    },
    {
        "url":"http://pbs.twimg.com/media/Df1AfKCX0AECGeD.jpg",
        "type":"photo",
        "text":"https://t.co/KtXbrKsZse",
        "user":"ramanaidugold",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfviuCxU0AMD1A4.jpg",
        "type":"photo",
        "text":"https://t.co/QuEhYkxOwu",
        "user":"budugodu",
        "retweetCount":33
    },
    {
        "url":"http://pbs.twimg.com/media/Df076BzUcAE-YjE.jpg",
        "type":"photo",
        "text":"https://t.co/C8znxVV7I8",
        "user":"phanireddyt",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df036kWWkAA905t.jpg",
        "type":"photo",
        "text":"https://t.co/ono8PwCAMq",
        "user":"_MarkChe",
        "retweetCount":8
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007993081533104128/pu/img/M5PwwSHfoQM-TFVM.jpg",
        "type":"photo",
        "text":"https://t.co/9eb4CL8mMk",
        "user":"Manikan87498732",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/Df1qCDgV4AA-j0D.jpg",
        "type":"photo",
        "text":"https://t.co/A4rUYjNpiO",
        "user":"mutyammajety",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1p3oAU8AA0s0v.jpg",
        "type":"photo",
        "text":"https://t.co/59EoS3zUvg",
        "user":"mutyammajety",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df0ZNsmXcAE4SwF.jpg",
        "type":"photo",
        "text":"https://t.co/zeHoc40cgH",
        "user":"pappu1232000",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/Df1ok5SU8AA3meq.jpg",
        "type":"photo",
        "text":"https://t.co/tdsGaQ0LpM",
        "user":"mutyammajety",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1mBDQV4AAX1iL.jpg",
        "type":"photo",
        "text":"https://t.co/kOTx6hRHuS",
        "user":"Sampath3570",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLGRCVAAUwBrn.jpg",
        "type":"photo",
        "text":"https://t.co/62kMWxbKOo",
        "user":"srikanthkumar7",
        "retweetCount":19
    },
    {
        "url":"http://pbs.twimg.com/media/Df1fwMHW0AAkbJB.jpg",
        "type":"photo",
        "text":"https://t.co/VYbqWuoNpP",
        "user":"Nani98323628",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df0dq_GUEAA_PRW.jpg",
        "type":"photo",
        "text":"https://t.co/noNh9j3WZc",
        "user":"ckvbalusu",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DfzNfhmUYAAV9_h.jpg",
        "type":"photo",
        "text":"https://t.co/1MDZ8NyPG3",
        "user":"durgaprasadvelp",
        "retweetCount":12
    },
    {
        "url":"http://pbs.twimg.com/media/Df1YneHUwAEYXV0.jpg",
        "type":"photo",
        "text":"https://t.co/E0czjOB9Qj",
        "user":"jcsekhar36",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfz4nKoWAAAv-dx.jpg",
        "type":"photo",
        "text":"https://t.co/ZsiyYWcK9R",
        "user":"SUNEELR83164292",
        "retweetCount":8
    },
    {
        "url":"http://pbs.twimg.com/media/Df1Ua9kUcAAut1F.jpg",
        "type":"photo",
        "text":"https://t.co/kTQ65uuHh4",
        "user":"AnjiEnugula",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfydJfbU8AA0nmC.jpg",
        "type":"photo",
        "text":"https://t.co/TcW5Ij9z8T",
        "user":"RaviDevarajK",
        "retweetCount":35
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007988235098718208/pu/img/yqvl_eaqu1XLfxYo.jpg",
        "type":"photo",
        "text":"https://t.co/KczAZJotxA",
        "user":"BhukyaRavinder3",
        "retweetCount":7
    },
    {
        "url":"http://pbs.twimg.com/media/Df1RPQ1V4AAb6mO.jpg",
        "type":"photo",
        "text":"https://t.co/NzvlLGqAvZ",
        "user":"RAGHU6611",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzL5m0UwAAcsLt.jpg",
        "type":"photo",
        "text":"https://t.co/Hvr5TTnrcu",
        "user":"rajashekar4336",
        "retweetCount":20
    },
    {
        "url":"http://pbs.twimg.com/media/Dcl9x84V4AAX2pT.jpg",
        "type":"photo",
        "text":"https://t.co/noJFmDPtGP",
        "user":"satish_siddhu",
        "retweetCount":6685
    },
    {
        "url":"http://pbs.twimg.com/media/DfdaPjPVAAAAOjb.jpg",
        "type":"photo",
        "text":"https://t.co/puh6ZdlhGY",
        "user":"Ramesh67743519",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfddPhUUYAAWr7K.jpg",
        "type":"photo",
        "text":"https://t.co/ghDwNQHhR4",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DfdbrGAVMAA4yYv.jpg",
        "type":"photo",
        "text":"https://t.co/FaaUQ3hB2e",
        "user":"Ramesh67743519",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DffS8G5VAAACEZB.jpg",
        "type":"photo",
        "text":"https://t.co/roLaacgP0Q",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DfdYBzEUwAAA_XE.jpg",
        "type":"photo",
        "text":"https://t.co/UiZFtHUgIF",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Dfda5vhW0AIUVUe.jpg",
        "type":"photo",
        "text":"https://t.co/CIDo09xQNc",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Df1ODtNW4AEUpiE.jpg",
        "type":"photo",
        "text":"https://t.co/WE2hBnAQSc",
        "user":"Pokiri_freaker",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfda1TCXkAI_23O.jpg",
        "type":"photo",
        "text":"https://t.co/yY7gjK5ybv",
        "user":"Ramesh67743519",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/DfeM2SUUEAAHJUV.jpg",
        "type":"photo",
        "text":"https://t.co/TXfCt7hNoV",
        "user":"Ramesh67743519",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZpj9UYAEUF3m.jpg",
        "type":"photo",
        "text":"https://t.co/0VOskXEQWy",
        "user":"Ramesh67743519",
        "retweetCount":8
    },
    {
        "url":"http://pbs.twimg.com/media/Dfu1ZJrUEAAbc1D.jpg",
        "type":"photo",
        "text":"https://t.co/eG7rj7Vqxb",
        "user":"DaguduKiran",
        "retweetCount":742
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZdpKU0AArVwz.jpg",
        "type":"photo",
        "text":"https://t.co/liovWIKUdD",
        "user":"Ramesh67743519",
        "retweetCount":6
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZUkhVMAAEmjq.jpg",
        "type":"photo",
        "text":"https://t.co/ZQSzKwmhjG",
        "user":"Ramesh67743519",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZKucVQAAvSZD.jpg",
        "type":"photo",
        "text":"https://t.co/1qexXmaVW5",
        "user":"Ramesh67743519",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfdY3j4VMAEsP3K.jpg",
        "type":"photo",
        "text":"https://t.co/zqVVSO8Zh9",
        "user":"Ramesh67743519",
        "retweetCount":16
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZ1WLUwAAsXWz.jpg",
        "type":"photo",
        "text":"https://t.co/r4wSHe892Y",
        "user":"Ramesh67743519",
        "retweetCount":4146
    },
    {
        "url":"http://pbs.twimg.com/media/DfuxP8PUEAADoc2.jpg",
        "type":"photo",
        "text":"https://t.co/8jRrh2CJUx",
        "user":"DaguduKiran",
        "retweetCount":974
    },
    {
        "url":"http://pbs.twimg.com/media/Df1MSMlWsAAYXcL.jpg",
        "type":"photo",
        "text":"https://t.co/bj3883OvRj",
        "user":"chantiadapa",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzK7RDUYAAJTX0.jpg",
        "type":"photo",
        "text":"https://t.co/dercjt5Dg9",
        "user":"sivakumar_01",
        "retweetCount":4187
    },
    {
        "url":"http://pbs.twimg.com/media/Df0eUp3VAAIsBWb.jpg",
        "type":"photo",
        "text":"https://t.co/kDYU4NTICj",
        "user":"MadhumathiPSPK",
        "retweetCount":4
    },
    {
        "url":"http://pbs.twimg.com/media/Dfu7FlrUYAEr2vE.jpg",
        "type":"photo",
        "text":"https://t.co/LwEyEMUh2L",
        "user":"HariBab99774197",
        "retweetCount":28
    },
    {
        "url":"http://pbs.twimg.com/media/Df0WZY7UEAAeOMC.jpg",
        "type":"photo",
        "text":"https://t.co/JcAJgg7Xjj",
        "user":"PoliticalSena",
        "retweetCount":71
    },
    {
        "url":"http://pbs.twimg.com/media/Df0BdQjUwAAw_mV.jpg",
        "type":"photo",
        "text":"https://t.co/rs39RQqlAR",
        "user":"Showbiz_IT",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfzy0QcUEAA6Gvx.jpg",
        "type":"photo",
        "text":"https://t.co/Busb3nZYyh",
        "user":"LMgroups",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzpPP4UYAAtURi.jpg",
        "type":"photo",
        "text":"https://t.co/EbeKNsP7FC",
        "user":"Poratayatra",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzcodJU8AAihqX.jpg",
        "type":"photo",
        "text":"https://t.co/lXEwp477wa",
        "user":"TollywoodTimes",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzbGiGU8AEHSuK.jpg",
        "type":"photo",
        "text":"https://t.co/mbPu4rmkYr",
        "user":"yursmonish",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzTQ_zUwAET1i-.jpg",
        "type":"photo",
        "text":"https://t.co/II1SV3kCRf",
        "user":"RaJeshJaNaSeNaa",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzSfUKUwAUE2IO.jpg",
        "type":"photo",
        "text":"https://t.co/jYDR03ABTf",
        "user":"Swetha__Says",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfu1tcrUEAAO00Q.jpg",
        "type":"photo",
        "text":"https://t.co/1Pf0f6WIjd",
        "user":"DURGASIVA2",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/DfzOf9PVMAAFImx.jpg",
        "type":"photo",
        "text":"https://t.co/7LdgZNSOUF",
        "user":"TeluguFS",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzM8BDU8AIlKGL.jpg",
        "type":"photo",
        "text":"https://t.co/H0ptceXmq3",
        "user":"991cc76dc609446",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzM3RSUwAAhAVb.jpg",
        "type":"photo",
        "text":"https://t.co/aB9rHYZNxf",
        "user":"Chinni_Pspk",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzMc0xVQAABsJE.jpg",
        "type":"photo",
        "text":"https://t.co/O4362V0FsR",
        "user":"rajeshkaipa",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLvzYVQAELuVz.jpg",
        "type":"photo",
        "text":"https://t.co/E698HVuOSh",
        "user":"Poratayatra",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzMPNMUEAAkslI.jpg",
        "type":"photo",
        "text":"https://t.co/OC4qItywaM",
        "user":"cineveduka",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLtqaUEAAm2jL.jpg",
        "type":"photo",
        "text":"https://t.co/8MySDKZy6E",
        "user":"V2Cinemas",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLYc8UcAIKNom.jpg",
        "type":"photo",
        "text":"https://t.co/scxalj0ie9",
        "user":"top10cinema",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLbMyV4AAo0aa.jpg",
        "type":"photo",
        "text":"https://t.co/CrrwwnLOsD",
        "user":"deepikapadukom",
        "retweetCount":320
    },
    {
        "url":"http://pbs.twimg.com/media/DfuFFhUUcAA-Cbp.jpg",
        "type":"photo",
        "text":"https://t.co/dtyBp5ewLz",
        "user":"Veeru23mayee",
        "retweetCount":7
    },
    {
        "url":"http://pbs.twimg.com/media/Dfuz0QHVQAM4O3A.jpg",
        "type":"photo",
        "text":"https://t.co/IGTwL0EvX6",
        "user":"sureshk79178702",
        "retweetCount":20
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLaWlVMAAwh74.jpg",
        "type":"photo",
        "text":"https://t.co/9UlpziyklA",
        "user":"rajesh7046",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLKfqUcAAuApD.jpg",
        "type":"photo",
        "text":"https://t.co/dCMfFLq8KL",
        "user":"durgeshcharan16",
        "retweetCount":17
    },
    {
        "url":"http://pbs.twimg.com/media/DfupZqrVQAEjRHR.jpg",
        "type":"photo",
        "text":"https://t.co/rnmKpd039w",
        "user":"BabupspkFan",
        "retweetCount":115
    },
    {
        "url":"http://pbs.twimg.com/media/DfztYtMW0AARXTN.jpg",
        "type":"photo",
        "text":"https://t.co/nD2lLoiAAY",
        "user":"AkhilShatagni",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/Dfvos4dVQAA0k9R.jpg",
        "type":"photo",
        "text":"https://t.co/ZV6PkEueNN",
        "user":"vamsinarayana2",
        "retweetCount":27
    },
    {
        "url":"http://pbs.twimg.com/media/DfzphYfUEAIgafR.jpg",
        "type":"photo",
        "text":"https://t.co/FynY5DTk9z",
        "user":"celebstelugu",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzM0UqVMAA6u7t.jpg",
        "type":"photo",
        "text":"https://t.co/q0afviao4I",
        "user":"0ae68f4fc3c44bc",
        "retweetCount":12
    },
    {
        "url":"http://pbs.twimg.com/media/DfzR-c2UYAApIDP.jpg",
        "type":"photo",
        "text":"https://t.co/tXKRIbcyTO",
        "user":"Sekarmba12",
        "retweetCount":9
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007845741816045568/pu/img/rfkNM-HuOe7rLEd8.jpg",
        "type":"photo",
        "text":"https://t.co/DMiRaIep1X",
        "user":"KalyanN02539704",
        "retweetCount":27
    },
    {
        "url":"http://pbs.twimg.com/media/DfzN_35U8AYsT0R.jpg",
        "type":"photo",
        "text":"https://t.co/89ZoNsErMW",
        "user":"sangame11652945",
        "retweetCount":11
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLrpxXUAEr61T.jpg",
        "type":"photo",
        "text":"https://t.co/auxFsgYbrh",
        "user":"adla_anand",
        "retweetCount":70
    },
    {
        "url":"http://pbs.twimg.com/media/Df5sEaKUEAE8AHS.jpg",
        "type":"photo",
        "text":"https://t.co/lIfC78AtP9",
        "user":"sena_akshay",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df5fr3rVMAEND5e.jpg",
        "type":"photo",
        "text":"https://t.co/3XMKpurP8l",
        "user":"sanjupowerstar2",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzzVyfWkAcHUoT.jpg",
        "type":"photo",
        "text":"https://t.co/Ui9tOPonKL",
        "user":"vijay_letsgo",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/Df5b9JiW0AAKrsk.jpg",
        "type":"photo",
        "text":"https://t.co/H4T6WaOttR",
        "user":"RamCharanTejFC",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLzWKV4AEgaP6.jpg",
        "type":"photo",
        "text":"https://t.co/R9sjukuB20",
        "user":"PspkHarish",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/Df5at7sVMAAsioX.jpg",
        "type":"photo",
        "text":"https://t.co/BzOSAx49Qh",
        "user":"InsidePolitics4",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dflrik2UEAAAktF.jpg",
        "type":"photo",
        "text":"https://t.co/fhfrUOLJSI",
        "user":"MaruthiGanesh3",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/Df4pRJrUwAAYEDy.jpg",
        "type":"photo",
        "text":"https://t.co/735cyvbV8d",
        "user":"rajaappikonda",
        "retweetCount":29
    },
    {
        "url":"http://pbs.twimg.com/media/Df4U-2hWAAA9Vkm.jpg",
        "type":"photo",
        "text":"https://t.co/mEha86OC2H",
        "user":"jigirijingania_",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df4LSpYV4AIS_T_.jpg",
        "type":"photo",
        "text":"https://t.co/1qf2HLBCpk",
        "user":"prathaprudra1",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfzk5BGW4AExw4-.jpg",
        "type":"photo",
        "text":"https://t.co/ulWphnZJxy",
        "user":"KuppalaV",
        "retweetCount":11
    },
    {
        "url":"http://pbs.twimg.com/media/Df3bqQcVAAAkZem.jpg",
        "type":"photo",
        "text":"https://t.co/w4xDIk1wuY",
        "user":"dexter_sadik",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzpGrRVAAAsZQz.jpg",
        "type":"photo",
        "text":"https://t.co/AJMEK3XD2L",
        "user":"tiru_live",
        "retweetCount":7
    },
    {
        "url":"http://pbs.twimg.com/media/DfzJaoMUwAEsytb.jpg",
        "type":"photo",
        "text":"https://t.co/k7lfIM25R4",
        "user":"sekharkona2",
        "retweetCount":6
    },
    {
        "url":"http://pbs.twimg.com/media/Dfz37w4U8AAEnfv.jpg",
        "type":"photo",
        "text":"https://t.co/Kxb4XcboEM",
        "user":"VazeerBasha11",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007873242747432961/pu/img/0QbnWVHO4LkVEkcm.jpg",
        "type":"photo",
        "text":"https://t.co/8k312nCAtk",
        "user":"Yakshitha7",
        "retweetCount":8
    },
    {
        "url":"http://pbs.twimg.com/media/Df1gqcWW4AEDIvI.jpg",
        "type":"photo",
        "text":"https://t.co/qjhkPAt3PU",
        "user":"OrangeArmyHYD",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzdWLAVQAAThXd.jpg",
        "type":"photo",
        "text":"https://t.co/aJgy9uLxD4",
        "user":"Kotieswar12",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/Df51DAfWsAAjAeH.jpg",
        "type":"photo",
        "text":"https://t.co/sDCI0YMjV3",
        "user":"manderton20",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df5xuzRXUAAKfDe.jpg",
        "type":"photo",
        "text":"https://t.co/g3kFvC4sBw",
        "user":"ChickenShop",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007700474395439105/pu/img/E4w6VLgoEbl_yX7s.jpg",
        "type":"photo",
        "text":"https://t.co/nLi22JWNjV",
        "user":"seshu219",
        "retweetCount":114
    },
    {
        "url":"http://pbs.twimg.com/media/Df5h1-rU8AEONcB.jpg",
        "type":"photo",
        "text":"https://t.co/X0f79q77KB",
        "user":"WorldPSPKFans",
        "retweetCount":7
    },
    {
        "url":"http://pbs.twimg.com/media/Df5fumpWkAA5JqN.jpg",
        "type":"photo",
        "text":"https://t.co/YZgwjskg94",
        "user":"charan4563",
        "retweetCount":13
    },
    {
        "url":"http://pbs.twimg.com/media/Df5UW5DX0AA7me0.jpg",
        "type":"photo",
        "text":"https://t.co/XxwkyqojdJ",
        "user":"AkhilShatagni",
        "retweetCount":4
    },
    {
        "url":"http://pbs.twimg.com/media/DfxpgVyU0AUfqNJ.jpg",
        "type":"photo",
        "text":"https://t.co/p3HSQ84aUv",
        "user":"chintu_pawanism",
        "retweetCount":23
    },
    {
        "url":"http://pbs.twimg.com/media/Df4ZfZMUYAApeow.jpg",
        "type":"photo",
        "text":"https://t.co/MxF2dIuBip",
        "user":"RatnasaiAlladi",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/Df1MgTBX4AAy8h_.jpg",
        "type":"photo",
        "text":"https://t.co/gz7YdxG0WQ",
        "user":"Syam19113sd26",
        "retweetCount":46
    },
    {
        "url":"http://pbs.twimg.com/media/Df4kq4-WAAMpC16.jpg",
        "type":"photo",
        "text":"https://t.co/sbv3TGHtTU",
        "user":"anil_mooga",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1008385270507438080/pu/img/AbIM22DSaGJU-qcz.jpg",
        "type":"photo",
        "text":"https://t.co/bfzALJwp6A",
        "user":"bonamsaibaba",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df6Bm5zX0AAUGHD.jpg",
        "type":"photo",
        "text":"https://t.co/HAAPdCIhpN",
        "user":"kulbair",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1012792873278951424/pu/img/UCkfLGqQMWFSbUzY.jpg",
        "type":"photo",
        "text":"https://t.co/T9CWv5WjZq",
        "user":"chintu002",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Dgx1U_MVMAAVwRi.jpg",
        "type":"photo",
        "text":"https://t.co/dkpSD6i5xA",
        "user":"9394022222jsp",
        "retweetCount":38
    },
    {
        "url":"http://pbs.twimg.com/media/Dg51T4vUwAAE_RW.jpg",
        "type":"photo",
        "text":"https://t.co/Y87CMaz4gF",
        "user":"9394022222jsp",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dg12YJhU0AEw138.jpg",
        "type":"photo",
        "text":"https://t.co/U4ynLRiRsF",
        "user":"JogiMohn",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DgwmNBEUwAA4-_A.jpg",
        "type":"photo",
        "text":"https://t.co/HtKNAf2TAl",
        "user":"Pawankalyan1981",
        "retweetCount":27
    },
    {
        "url":"http://pbs.twimg.com/media/DgyQbsXUYAAC6aM.jpg",
        "type":"photo",
        "text":"https://t.co/3bJtvYOatA",
        "user":"Pawankalyan1981",
        "retweetCount":9
    },
    {
        "url":"http://pbs.twimg.com/media/Dg5KX6cUwAAgRDz.jpg",
        "type":"photo",
        "text":"https://t.co/YlmnJ4wXrd",
        "user":"ImPkCult",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dg4_qjYU0AA_O9W.jpg",
        "type":"photo",
        "text":"https://t.co/2KnORuLVWN",
        "user":"ImPkCult",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1011466741426212864/pu/img/6O14n14vA3B-c8rU.jpg",
        "type":"photo",
        "text":"https://t.co/N8ROofVpMF",
        "user":"PrasanthKonide3",
        "retweetCount":402
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1011678572493266944/pu/img/JXA_vVZX6MIP1eHq.jpg",
        "type":"photo",
        "text":"https://t.co/Vb9TpJlTN1",
        "user":"Akhil80622666",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/DQH_6yXUEAA5Vlb.jpg",
        "type":"photo",
        "text":"https://t.co/TgDUB7T62Q",
        "user":"charan4563",
        "retweetCount":352
    },
    {
        "url":"http://pbs.twimg.com/media/DgzO95eU8AAW5cU.jpg",
        "type":"photo",
        "text":"https://t.co/3pru7TluST",
        "user":"DHEERAJPSPKFAN",
        "retweetCount":38
    },
    {
        "url":"http://pbs.twimg.com/media/Dg32XXaVMAIJCWV.jpg",
        "type":"photo",
        "text":"https://t.co/swKTsnN533",
        "user":"PawanKalyan_off",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dg3z5V0VAAAitij.jpg",
        "type":"photo",
        "text":"https://t.co/B1z7OycwGB",
        "user":"BangJSHaters",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Dg1uLQvV4AAJ4RX.jpg",
        "type":"photo",
        "text":"https://t.co/5MoV4A0i4s",
        "user":"GopiAnnem",
        "retweetCount":19
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1012263904934703104/pu/img/4__2YD87S_akMlVC.jpg",
        "type":"photo",
        "text":"https://t.co/iPEoyKcvC9",
        "user":"ssk_twiter",
        "retweetCount":19
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1012355517333884928/pu/img/OD8WQmhQFkPh6obz.jpg",
        "type":"photo",
        "text":"https://t.co/2D1ixmRKSx",
        "user":"Palla11284266",
        "retweetCount":26
    },
    {
        "url":"http://pbs.twimg.com/media/Dgstwx4U0AE1DDQ.jpg",
        "type":"photo",
        "text":"https://t.co/zX7AviLmBs",
        "user":"srikanth1868",
        "retweetCount":46
    },
    {
        "url":"http://pbs.twimg.com/media/Dg3hcSCV4AEgHAc.jpg",
        "type":"photo",
        "text":"https://t.co/37rp1xeIVI",
        "user":"PawanVijayFC",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DgtR_gUXcAEA2dP.jpg",
        "type":"photo",
        "text":"https://t.co/fjjM7kTp45",
        "user":"Pavankrisnna90",
        "retweetCount":206
    },
    {
        "url":"http://pbs.twimg.com/media/Dg23rI5W0AETAKx.jpg",
        "type":"photo",
        "text":"https://t.co/JZvnKAgZ17",
        "user":"Yakshitha7",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DgyRz8sVQAAGXQU.jpg",
        "type":"photo",
        "text":"https://t.co/Vbv40XRuNm",
        "user":"chandus27",
        "retweetCount":47
    },
    {
        "url":"http://pbs.twimg.com/media/Dg3ZcvfUEAMhnHF.jpg",
        "type":"photo",
        "text":"https://t.co/L9ozvMmcAQ",
        "user":"NenuAnteNene",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dg232T5WAAIIB4D.jpg",
        "type":"photo",
        "text":"https://t.co/D9rMM4A8Xp",
        "user":"JanasenaMissile",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Df1NaJdUcAAyB9l.jpg",
        "type":"photo",
        "text":"https://t.co/DmqqmbmPFg",
        "user":"Babaji28877482",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/Dg3XcJPVQAMElMa.jpg",
        "type":"photo",
        "text":"https://t.co/X2HS1va2dj",
        "user":"IamKalyanRaksha",
        "retweetCount":9
    },
    {
        "url":"http://pbs.twimg.com/media/Dg2Q3lGX4AArCAA.jpg",
        "type":"photo",
        "text":"https://t.co/0ZYnvsavXI",
        "user":"BabupspkFan",
        "retweetCount":21
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1012591659815538688/pu/img/yYY9ncjbHzkhxTdo.jpg",
        "type":"photo",
        "text":"https://t.co/C5SHWenqj9",
        "user":"vamsiNa18622526",
        "retweetCount":32
    },
    {
        "url":"http://pbs.twimg.com/media/Dg3Ni8EUEAAKUWT.jpg",
        "type":"photo",
        "text":"https://t.co/2XiWv91PlH",
        "user":"MentalAlways",
        "retweetCount":29
    },
    {
        "url":"http://pbs.twimg.com/media/DgdBxe7UwAAru6r.jpg",
        "type":"photo",
        "text":"https://t.co/KkKrvrtbXT",
        "user":"Pawankalyan1981",
        "retweetCount":829
    },
    {
        "url":"http://pbs.twimg.com/media/Dg5aIe-VMAAmH1g.jpg",
        "type":"photo",
        "text":"https://t.co/rmtNaPzcXr",
        "user":"bkrsatish",
        "retweetCount":6
    },
    {
        "url":"http://pbs.twimg.com/media/Dg1uGhLU8AEnY-V.jpg",
        "type":"photo",
        "text":"https://t.co/giv2HVyova",
        "user":"jspspeaker",
        "retweetCount":42
    },
    {
        "url":"http://pbs.twimg.com/media/DgysunVW4AwLNHT.jpg",
        "type":"photo",
        "text":"https://t.co/ZLiP6paVx1",
        "user":"VenuCherryDasi",
        "retweetCount":4
    },
    {
        "url":"http://pbs.twimg.com/media/Dg0nttiUEAAwzVX.jpg",
        "type":"photo",
        "text":"https://t.co/sgKOW62LTo",
        "user":"YerraJagan",
        "retweetCount":7
    },
    {
        "url":"http://pbs.twimg.com/media/DbTg4HGV4AAXhgE.jpg",
        "type":"photo",
        "text":"https://t.co/zxOSmw8iRh",
        "user":"AyanPawanist_",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/Dg1qthAU8AIVhx6.jpg",
        "type":"photo",
        "text":"https://t.co/1u2YED9lMt",
        "user":"dasurya65039341",
        "retweetCount":31
    },
    {
        "url":"http://pbs.twimg.com/media/Dg1NGoyUwAAhlvO.jpg",
        "type":"photo",
        "text":"https://t.co/gn5kOuxlv7",
        "user":"kotipapaganti01",
        "retweetCount":11
    },
    {
        "url":"http://pbs.twimg.com/media/Dg1CI1CX4AAPtTH.jpg",
        "type":"photo",
        "text":"https://t.co/E2ss4T6P2q",
        "user":"_MarkChe",
        "retweetCount":11
    },
    {
        "url":"http://pbs.twimg.com/media/Dgx9GVTXcAIoz7X.jpg",
        "type":"photo",
        "text":"https://t.co/SrrqVCvWjy",
        "user":"JRodneyPage",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dg5ie-MX0AE2Gei.jpg",
        "type":"photo",
        "text":"https://t.co/t6FS5zRuLQ",
        "user":"ranigill7",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1013047650680168449/pu/img/hBm43PrpTNe3rrps.jpg",
        "type":"photo",
        "text":"https://t.co/WAavtowCNP",
        "user":"sakshinews",
        "retweetCount":3
    }
];


export const sampleYouTubeData= [
    {
        "id": 1,
        "videoID": "72ECcN8MsVc",
        "title": "Nara Lokesh Dance Performance  - TDP Minister",
        "positive": 0,
        "negative": 0,
        "mixed": 0,
        "createdAt": "2018-07-12T23:00:35.487+0000",
        "updatedAt": "2018-07-12T23:00:35.487+0000"
    },
    {
        "id": 2,
        "videoID": "tnG-Rj7dVaM",
        "title": "TG Venkatesh Sensational Comments On Minister Nara Lokesh ll Pulihora News",
        "positive": 13,
        "negative": 0,
        "mixed": 0,
        "createdAt": "2018-07-12T23:00:35.552+0000",
        "updatedAt": "2018-07-12T23:00:35.552+0000"
    },
    {
        "id": 3,
        "videoID": "zPsziwxzOPs",
        "title": "లోకేష్ పై టీజీ ఫైర్ ! | TG Venkatesh slams Nara Lokesh | AP Elections | Newsmarg",
        "positive": 10,
        "negative": 0,
        "mixed": 0,
        "createdAt": "2018-07-12T23:00:35.597+0000",
        "updatedAt": "2018-07-12T23:00:35.597+0000"
    },
    {
        "id": 4,
        "videoID": "bM7v5PI7BmA",
        "title": "Nara Lokesh Requests TDP Ministers to Start Booth level Campaigns | Overseas News",
        "positive": 0,
        "negative": 0,
        "mixed": 0,
        "createdAt": "2018-07-12T23:00:35.665+0000",
        "updatedAt": "2018-07-12T23:00:35.665+0000"
    }
];