export const sampleData= [
    {
        "url":"http://pbs.twimg.com/media/Df1eFiTUYAAbsrQ.jpg",
        "type":"photo",
        "text":"https://t.co/1tNHwnySVh",
        "user":"SURESHK96385865",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1XjdMW4AAgFOh.jpg",
        "type":"photo",
        "text":"https://t.co/qFMZed6Ii5",
        "user":"katipallyvinay",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1WApuXcAAbnMy.jpg",
        "type":"photo",
        "text":"https://t.co/c3XHw6XqSa",
        "user":"tdpnanda",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Df1O2mFUEAAod76.jpg",
        "type":"photo",
        "text":"https://t.co/xEE4t7xt1W",
        "user":"isocialsaint",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DftoVifU8AAWpnI.jpg",
        "type":"photo",
        "text":"https://t.co/Dbmxac89uF",
        "user":"istam_na",
        "retweetCount":58
    },
    {
        "url":"http://pbs.twimg.com/media/Df1Iab-VMAA2760.jpg",
        "type":"photo",
        "text":"https://t.co/69TMA87Xlf",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1IN1gUcAA_Sds.jpg",
        "type":"photo",
        "text":"https://t.co/q1zmhWM6JS",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1HWqzU0AAfjkK.jpg",
        "type":"photo",
        "text":"https://t.co/47mo980xNR",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfgk2zTV4AADA3x.jpg",
        "type":"photo",
        "text":"https://t.co/UKIEVHvr1M",
        "user":"PranayOfficial",
        "retweetCount":116
    },
    {
        "url":"http://pbs.twimg.com/media/Df1GUceVQAAAjXU.jpg",
        "type":"photo",
        "text":"https://t.co/gSHhppU4Fx",
        "user":"NagarajuRayudu",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1008038739048722432/pu/img/sQXv-Z0bVYSYsAQN.jpg",
        "type":"photo",
        "text":"https://t.co/KEJne48jDT",
        "user":"JoshuaJoe95",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfuriA_VMAAvyO0.jpg",
        "type":"photo",
        "text":"https://t.co/STuTfcC3CF",
        "user":"nbkmyheart3",
        "retweetCount":6
    },
    {
        "url":"http://pbs.twimg.com/media/Df1AfKCX0AECGeD.jpg",
        "type":"photo",
        "text":"https://t.co/KtXbrKsZse",
        "user":"ramanaidugold",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfviuCxU0AMD1A4.jpg",
        "type":"photo",
        "text":"https://t.co/QuEhYkxOwu",
        "user":"budugodu",
        "retweetCount":33
    },
    {
        "url":"http://pbs.twimg.com/media/Df076BzUcAE-YjE.jpg",
        "type":"photo",
        "text":"https://t.co/C8znxVV7I8",
        "user":"phanireddyt",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df036kWWkAA905t.jpg",
        "type":"photo",
        "text":"https://t.co/ono8PwCAMq",
        "user":"_MarkChe",
        "retweetCount":8
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007993081533104128/pu/img/M5PwwSHfoQM-TFVM.jpg",
        "type":"photo",
        "text":"https://t.co/9eb4CL8mMk",
        "user":"Manikan87498732",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/Df1qCDgV4AA-j0D.jpg",
        "type":"photo",
        "text":"https://t.co/A4rUYjNpiO",
        "user":"mutyammajety",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1p3oAU8AA0s0v.jpg",
        "type":"photo",
        "text":"https://t.co/59EoS3zUvg",
        "user":"mutyammajety",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df0ZNsmXcAE4SwF.jpg",
        "type":"photo",
        "text":"https://t.co/zeHoc40cgH",
        "user":"pappu1232000",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/Df1ok5SU8AA3meq.jpg",
        "type":"photo",
        "text":"https://t.co/tdsGaQ0LpM",
        "user":"mutyammajety",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df1mBDQV4AAX1iL.jpg",
        "type":"photo",
        "text":"https://t.co/kOTx6hRHuS",
        "user":"Sampath3570",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLGRCVAAUwBrn.jpg",
        "type":"photo",
        "text":"https://t.co/62kMWxbKOo",
        "user":"srikanthkumar7",
        "retweetCount":19
    },
    {
        "url":"http://pbs.twimg.com/media/Df1fwMHW0AAkbJB.jpg",
        "type":"photo",
        "text":"https://t.co/VYbqWuoNpP",
        "user":"Nani98323628",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Df0dq_GUEAA_PRW.jpg",
        "type":"photo",
        "text":"https://t.co/noNh9j3WZc",
        "user":"ckvbalusu",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DfzNfhmUYAAV9_h.jpg",
        "type":"photo",
        "text":"https://t.co/1MDZ8NyPG3",
        "user":"durgaprasadvelp",
        "retweetCount":12
    },
    {
        "url":"http://pbs.twimg.com/media/Df1YneHUwAEYXV0.jpg",
        "type":"photo",
        "text":"https://t.co/E0czjOB9Qj",
        "user":"jcsekhar36",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfz4nKoWAAAv-dx.jpg",
        "type":"photo",
        "text":"https://t.co/ZsiyYWcK9R",
        "user":"SUNEELR83164292",
        "retweetCount":8
    },
    {
        "url":"http://pbs.twimg.com/media/Df1Ua9kUcAAut1F.jpg",
        "type":"photo",
        "text":"https://t.co/kTQ65uuHh4",
        "user":"AnjiEnugula",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfydJfbU8AA0nmC.jpg",
        "type":"photo",
        "text":"https://t.co/TcW5Ij9z8T",
        "user":"RaviDevarajK",
        "retweetCount":35
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007988235098718208/pu/img/yqvl_eaqu1XLfxYo.jpg",
        "type":"photo",
        "text":"https://t.co/KczAZJotxA",
        "user":"BhukyaRavinder3",
        "retweetCount":7
    },
    {
        "url":"http://pbs.twimg.com/media/Df09hfvUYAAWAA_.jpg",
        "type":"photo",
        "text":"https://t.co/sGyJCsCqva",
        "user":"vrb71",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/Df1RPQ1V4AAb6mO.jpg",
        "type":"photo",
        "text":"https://t.co/NzvlLGqAvZ",
        "user":"RAGHU6611",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzL5m0UwAAcsLt.jpg",
        "type":"photo",
        "text":"https://t.co/Hvr5TTnrcu",
        "user":"rajashekar4336",
        "retweetCount":20
    },
    {
        "url":"http://pbs.twimg.com/media/Dcl9x84V4AAX2pT.jpg",
        "type":"photo",
        "text":"https://t.co/noJFmDPtGP",
        "user":"satish_siddhu",
        "retweetCount":6685
    },
    {
        "url":"http://pbs.twimg.com/media/DfdaPjPVAAAAOjb.jpg",
        "type":"photo",
        "text":"https://t.co/puh6ZdlhGY",
        "user":"Ramesh67743519",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfddPhUUYAAWr7K.jpg",
        "type":"photo",
        "text":"https://t.co/ghDwNQHhR4",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DfdbrGAVMAA4yYv.jpg",
        "type":"photo",
        "text":"https://t.co/FaaUQ3hB2e",
        "user":"Ramesh67743519",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DffS8G5VAAACEZB.jpg",
        "type":"photo",
        "text":"https://t.co/roLaacgP0Q",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/DfdYBzEUwAAA_XE.jpg",
        "type":"photo",
        "text":"https://t.co/UiZFtHUgIF",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Dfda5vhW0AIUVUe.jpg",
        "type":"photo",
        "text":"https://t.co/CIDo09xQNc",
        "user":"Ramesh67743519",
        "retweetCount":2
    },
    {
        "url":"http://pbs.twimg.com/media/Df1ODtNW4AEUpiE.jpg",
        "type":"photo",
        "text":"https://t.co/WE2hBnAQSc",
        "user":"Pokiri_freaker",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfda1TCXkAI_23O.jpg",
        "type":"photo",
        "text":"https://t.co/yY7gjK5ybv",
        "user":"Ramesh67743519",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/DfeM2SUUEAAHJUV.jpg",
        "type":"photo",
        "text":"https://t.co/TXfCt7hNoV",
        "user":"Ramesh67743519",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZpj9UYAEUF3m.jpg",
        "type":"photo",
        "text":"https://t.co/0VOskXEQWy",
        "user":"Ramesh67743519",
        "retweetCount":8
    },
    {
        "url":"http://pbs.twimg.com/media/Dfu1ZJrUEAAbc1D.jpg",
        "type":"photo",
        "text":"https://t.co/eG7rj7Vqxb",
        "user":"DaguduKiran",
        "retweetCount":742
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZdpKU0AArVwz.jpg",
        "type":"photo",
        "text":"https://t.co/liovWIKUdD",
        "user":"Ramesh67743519",
        "retweetCount":6
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZUkhVMAAEmjq.jpg",
        "type":"photo",
        "text":"https://t.co/ZQSzKwmhjG",
        "user":"Ramesh67743519",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZKucVQAAvSZD.jpg",
        "type":"photo",
        "text":"https://t.co/1qexXmaVW5",
        "user":"Ramesh67743519",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfdY3j4VMAEsP3K.jpg",
        "type":"photo",
        "text":"https://t.co/zqVVSO8Zh9",
        "user":"Ramesh67743519",
        "retweetCount":16
    },
    {
        "url":"http://pbs.twimg.com/media/DfdZ1WLUwAAsXWz.jpg",
        "type":"photo",
        "text":"https://t.co/r4wSHe892Y",
        "user":"Ramesh67743519",
        "retweetCount":4146
    },
    {
        "url":"http://pbs.twimg.com/media/DfuxP8PUEAADoc2.jpg",
        "type":"photo",
        "text":"https://t.co/8jRrh2CJUx",
        "user":"DaguduKiran",
        "retweetCount":974
    },
    {
        "url":"http://pbs.twimg.com/media/Df1MSMlWsAAYXcL.jpg",
        "type":"photo",
        "text":"https://t.co/bj3883OvRj",
        "user":"chantiadapa",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzK7RDUYAAJTX0.jpg",
        "type":"photo",
        "text":"https://t.co/dercjt5Dg9",
        "user":"sivakumar_01",
        "retweetCount":4187
    },
    {
        "url":"http://pbs.twimg.com/media/Df0eUp3VAAIsBWb.jpg",
        "type":"photo",
        "text":"https://t.co/kDYU4NTICj",
        "user":"MadhumathiPSPK",
        "retweetCount":4
    },
    {
        "url":"http://pbs.twimg.com/media/Dfu7FlrUYAEr2vE.jpg",
        "type":"photo",
        "text":"https://t.co/LwEyEMUh2L",
        "user":"HariBab99774197",
        "retweetCount":28
    },
    {
        "url":"http://pbs.twimg.com/media/Df0WZY7UEAAeOMC.jpg",
        "type":"photo",
        "text":"https://t.co/JcAJgg7Xjj",
        "user":"PoliticalSena",
        "retweetCount":71
    },
    {
        "url":"http://pbs.twimg.com/media/Df0BdQjUwAAw_mV.jpg",
        "type":"photo",
        "text":"https://t.co/rs39RQqlAR",
        "user":"Showbiz_IT",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfz37w4U8AAEnfv.jpg",
        "type":"photo",
        "text":"https://t.co/Kxb4XcboEM",
        "user":"mkrishnaraom",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfzy0QcUEAA6Gvx.jpg",
        "type":"photo",
        "text":"https://t.co/Busb3nZYyh",
        "user":"LMgroups",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzphYfUEAIgafR.jpg",
        "type":"photo",
        "text":"https://t.co/FynY5DTk9z",
        "user":"celebstelugu",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzpPP4UYAAtURi.jpg",
        "type":"photo",
        "text":"https://t.co/EbeKNsP7FC",
        "user":"Poratayatra",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzdWLAVQAAThXd.jpg",
        "type":"photo",
        "text":"https://t.co/aJgy9uLxD4",
        "user":"mkrishnaraom",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzcodJU8AAihqX.jpg",
        "type":"photo",
        "text":"https://t.co/lXEwp477wa",
        "user":"TollywoodTimes",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzbGiGU8AEHSuK.jpg",
        "type":"photo",
        "text":"https://t.co/mbPu4rmkYr",
        "user":"yursmonish",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzTQ_zUwAET1i-.jpg",
        "type":"photo",
        "text":"https://t.co/II1SV3kCRf",
        "user":"RaJeshJaNaSeNaa",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzSfUKUwAUE2IO.jpg",
        "type":"photo",
        "text":"https://t.co/jYDR03ABTf",
        "user":"Swetha__Says",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/Dfu1tcrUEAAO00Q.jpg",
        "type":"photo",
        "text":"https://t.co/1Pf0f6WIjd",
        "user":"DURGASIVA2",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/DfzOf9PVMAAFImx.jpg",
        "type":"photo",
        "text":"https://t.co/7LdgZNSOUF",
        "user":"TeluguFS",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzM8BDU8AIlKGL.jpg",
        "type":"photo",
        "text":"https://t.co/H0ptceXmq3",
        "user":"991cc76dc609446",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzM3RSUwAAhAVb.jpg",
        "type":"photo",
        "text":"https://t.co/aB9rHYZNxf",
        "user":"Chinni_Pspk",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzMc0xVQAABsJE.jpg",
        "type":"photo",
        "text":"https://t.co/O4362V0FsR",
        "user":"rajeshkaipa",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLvzYVQAELuVz.jpg",
        "type":"photo",
        "text":"https://t.co/E698HVuOSh",
        "user":"Poratayatra",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzMPNMUEAAkslI.jpg",
        "type":"photo",
        "text":"https://t.co/OC4qItywaM",
        "user":"cineveduka",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLtqaUEAAm2jL.jpg",
        "type":"photo",
        "text":"https://t.co/8MySDKZy6E",
        "user":"V2Cinemas",
        "retweetCount":1
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLYc8UcAIKNom.jpg",
        "type":"photo",
        "text":"https://t.co/scxalj0ie9",
        "user":"top10cinema",
        "retweetCount":0
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLbMyV4AAo0aa.jpg",
        "type":"photo",
        "text":"https://t.co/CrrwwnLOsD",
        "user":"deepikapadukom",
        "retweetCount":320
    },
    {
        "url":"http://pbs.twimg.com/media/DfzJaoMUwAEsytb.jpg",
        "type":"photo",
        "text":"https://t.co/k7lfIM25R4",
        "user":"KiranSure",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/Df1NaJdUcAAyB9l.jpg",
        "type":"photo",
        "text":"https://t.co/DmqqmbmPFg",
        "user":"SravanipspkFan",
        "retweetCount":4
    },
    {
        "url":"http://pbs.twimg.com/media/Df1MgTBX4AAy8h_.jpg",
        "type":"photo",
        "text":"https://t.co/gz7YdxG0WQ",
        "user":"jspsathagni",
        "retweetCount":11
    },
    {
        "url":"http://pbs.twimg.com/media/DfuFFhUUcAA-Cbp.jpg",
        "type":"photo",
        "text":"https://t.co/dtyBp5ewLz",
        "user":"Veeru23mayee",
        "retweetCount":7
    },
    {
        "url":"http://pbs.twimg.com/media/DfzM0UqVMAA6u7t.jpg",
        "type":"photo",
        "text":"https://t.co/q0afviao4I",
        "user":"AyanPawanist_",
        "retweetCount":12
    },
    {
        "url":"http://pbs.twimg.com/media/Dfuz0QHVQAM4O3A.jpg",
        "type":"photo",
        "text":"https://t.co/IGTwL0EvX6",
        "user":"sureshk79178702",
        "retweetCount":20
    },
    {
        "url":"http://pbs.twimg.com/media/DfzpGrRVAAAsZQz.jpg",
        "type":"photo",
        "text":"https://t.co/AJMEK3XD2L",
        "user":"ASKwithPSPK",
        "retweetCount":5
    },
    {
        "url":"http://pbs.twimg.com/media/DfzzVyfWkAcHUoT.jpg",
        "type":"photo",
        "text":"https://t.co/Ui9tOPonKL",
        "user":"NTVJustIn",
        "retweetCount":4
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007700474395439105/pu/img/E4w6VLgoEbl_yX7s.jpg",
        "type":"photo",
        "text":"https://t.co/nLi22JWNjV",
        "user":"rajesh7046",
        "retweetCount":97
    },
    {
        "url":"http://pbs.twimg.com/ext_tw_video_thumb/1007845741816045568/pu/img/rfkNM-HuOe7rLEd8.jpg",
        "type":"photo",
        "text":"https://t.co/DMiRaIep1X",
        "user":"rajesh7046",
        "retweetCount":27
    },
    {
        "url":"http://pbs.twimg.com/media/Dfzk5BGW4AExw4-.jpg",
        "type":"photo",
        "text":"https://t.co/ulWphnZJxy",
        "user":"Balu23r",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLzWKV4AEgaP6.jpg",
        "type":"photo",
        "text":"https://t.co/R9sjukuB20",
        "user":"rajesh7046",
        "retweetCount":9
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLaWlVMAAwh74.jpg",
        "type":"photo",
        "text":"https://t.co/9UlpziyklA",
        "user":"rajesh7046",
        "retweetCount":10
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLrpxXUAEr61T.jpg",
        "type":"photo",
        "text":"https://t.co/auxFsgYbrh",
        "user":"Pashiii2425",
        "retweetCount":70
    },
    {
        "url":"http://pbs.twimg.com/media/DfzLKfqUcAAuApD.jpg",
        "type":"photo",
        "text":"https://t.co/dCMfFLq8KL",
        "user":"durgeshcharan16",
        "retweetCount":17
    },
    {
        "url":"http://pbs.twimg.com/media/DfzN_35U8AYsT0R.jpg",
        "type":"photo",
        "text":"https://t.co/89ZoNsErMW",
        "user":"Rajashekara_DR",
        "retweetCount":11
    },
    {
        "url":"http://pbs.twimg.com/media/DfupZqrVQAEjRHR.jpg",
        "type":"photo",
        "text":"https://t.co/rnmKpd039w",
        "user":"BabupspkFan",
        "retweetCount":115
    },
    {
        "url":"http://pbs.twimg.com/media/DfzR-c2UYAApIDP.jpg",
        "type":"photo",
        "text":"https://t.co/tXKRIbcyTO",
        "user":"mohdmustafa3333",
        "retweetCount":9
    },
    {
        "url":"http://pbs.twimg.com/media/DfztYtMW0AARXTN.jpg",
        "type":"photo",
        "text":"https://t.co/nD2lLoiAAY",
        "user":"AkhilShatagni",
        "retweetCount":3
    },
    {
        "url":"http://pbs.twimg.com/media/Dfvos4dVQAA0k9R.jpg",
        "type":"photo",
        "text":"https://t.co/ZV6PkEueNN",
        "user":"vamsinarayana2",
        "retweetCount":27
    }
];